### ISSUE TITLE
Bugfix: AreTomo does not run if extra kwargs are empty

### ISSUE THREAD

**Issue by elainehoml** [rosalindfranklininstitute/Ot2Rec#45]
Error when calling `o2r.aretomo.run` on a aretomo yaml with no extra kwargs added

## Expected Behavior
If no kwargs are specified, no additional arguments should be appended to the command to run the desired AreTomo process.

## Current Behavior
`o2r.aretomo.run` exits with an error if kwargs list is empty. Though the o2r.aretomo.new part works - which is why all the tests have passed as the tests do not cover `o2r.aretomo.run`.

## Possible Solution
Add a if loop to only append arguments to the command for running AreTomo when `params['AreTomo_kwargs']` is not empty.

## Steps to Reproduce

Using the demo dataset, after motioncorr has been done
1. `o2r.aretomo.new TS 0 90`
2. `o2r.aretomo.run TS 0`

Or using the demo dataset after alignment has been done
1. `o2r.aretomo.new TS 1 90 --volz 200`
5. `o2r.aretomo.run TS 1`

**Comment by MasterVexillen** [comment]
May be closing this one as we're now using the MagicGUI implementation?
