### ISSUE TITLE
Bugfix: Motioncor2 CPU only option not working

### ISSUE THREAD

**Issue by elainehoml** [rosalindfranklininstitute/Ot2Rec#54]
When running `v0.2.4` motioncor step, I get the following error when the "use CPU only" option is ticked.

```
ValueError: Error in metadata._get_gpu_from_nvidia_smi: 1 GPU detected, but none of them is free.
```

**Comment by MasterVexillen** [comment]
CPU-only option was for testing and is obsolete. Will be removed in this bugfix.
